name: poly_pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - salmon
  - star
  - openpyxl
  - samtools
  - biopython
  - pyfaidx
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - tqdm
  - python-dotenv
  - pathlib2
  - rich
  - loguru
  - ipykernel
  - jupyterlab
  - blast
  - pandas
  - squashfs-tools
  - wget
  - pkg-config
  - git
  - pip
  - pip:
      - pyexcel-ods
